### PR TITLE
Update parsing payment msg

### PR DESCRIPTION
**Pull request by deniz-valeo**
Adapt the parsing for payment option

### CODE REVIEW

**Comment by mhugo** [comment]
So if I understand correctly, some fields have not the same value between josev iso15118 in rust and in python ? 

https://josev-api.ecog.io/v1.6.6/external_messages/iso15118_state_info

**Comment by deniz-valeo** [comment]
Yes I guess, I see the payment option field is now "selectedPaymentOption":"PnC" (piso) which was "selected_payment_option":"PNC" (riso)

**Comment by mhugo** [comment]
Ok, could you add a comment in the code explaining that this part will only work with python-iso15118 and not the rust version anymore ? I guess this is a regression issue in josev's code, maybe we should also warn EcoG about it

**Comment by deniz-valeo** [comment]
Yes, I agree. The comment is added as well

**Review by mhugo — APPROVED** [review]

**Pull request merged**
